site_name: Garden
repo_url: https://github.com/pulsgarney/garden
site_url: https://pulsgarney.github.io/garden
site_description: Garden is a simple asynchronous task management library for Python.
site_author: Puls Garney
copyright: © 2025 Garden. All rights reserved.
theme: readthedocs
plugins:
  - search
  - mermaid2
nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - Concepts:
    - Gardener: concepts/gardener.md
    - Hedgehog: concepts/hedgehog.md
    - Tasks: concepts/tasks.md
    - Middleware: concepts/middleware.md
  - Examples:
    - Lifecycle: examples/lifecycle.md
    - MongoDB: examples/mongodb.md
    - Redis: examples/redis.md
    - Selenium: examples/selenium.md
    - State: examples/state.md
  - Development:
    - Middlewares: development/middlewares.md
  - References:
    - Architecture: references/architecture.md
    - Lifecycle: references/lifecycle.md
    - Changelog: changelog.md
